name: Create and close weekly team meeting issue
on:
  workflow_dispatch
  schedule:
  ## Wednesday of every week @ 00:00 UTC (Wednesday AEDT) for Tue meeting the following week
  - cron: '00 08 * * WED'
jobs:
  find_old_issue:
    name: Find old team meeting meeting issue
    runs-on: ubuntu-latest
    outputs:
      meeting_id: ${{ steps.meeting.outputs.issue_id }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: meeting
        run: echo "::set-output name=issue_id::$(gh issue list -s open -l 'agenda' --json number -q '.[0].number')"

  close_old_issue:
    name: Close old team meeting issue
    runs-on: ubuntu-latest
    needs: find_old_issue
    if: ${{needs.find_old_issue.outputs.meeting_id}}
    steps:
      - uses: actions/checkout@master
      - name: Close old meeting issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            gh issue close ${{needs.find_old_issue.outputs.meeting_id}}
  create_new_meeting_issue:
    name: Create new team meeting issue
    runs-on: ubuntu-latest
    if: always()
    needs: [find_old_issue, close_old_issue]
    steps:
    - uses: actions/checkout@master
    - uses: JasonEtco/create-an-issue@v2
      env:
        LAST_WEEK_MEETING_ID: ${{needs.find_old_issue.outputs.meeting_id}}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/ISSUE_TEMPLATE/auto-weekly/team-meeting.md
